# Generated by Django 5.0 on 2023-12-15 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('achievement_type', models.CharField(choices=[('1', 'Academic'), ('2', 'Non-Academic')], max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='achievement_files/')),
                ('image_url', models.URLField()),
                ('approved', models.BooleanField()),
                ('approved_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.faculty')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
