# Generated by Django 4.2.4 on 2023-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_studentachievement_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentachievement',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
