# Generated by Django 4.2.4 on 2023-12-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_studentachievement_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentachievement',
            name='file',
            field=models.ImageField(upload_to='achievement_files/'),
        ),
    ]
